[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"

# ESTA ES LA SECCIÓN CLAVE PARA LAS FUNCIONES
[functions]
  directory = "netlify/functions"

# --- AÑADE ESTAS NUEVAS REGLAS AQUÍ ---
[[redirects]]
  from = "/terminos.html"
  to = "/terminos.html"
  status = 200

[[redirects]]
  from = "/privacidad.html"
  to = "/privacidad.html"
  status = 200

[[redirects]]
  from = "/reembolso.html"
  to = "/reembolso.html"
  status = 200
# ----------------------------------------

# La regla "catch-all" que ya tenías, pero ahora al final
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200